version: '3'
services:
  db:
    image: postgres:latest
    container_name: bancoDados
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AP1c3la!123
      POSTGRES_DB: apicela
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql

       
  apicela_aiko_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apicela_aiko
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/apicela
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=AP1c3la!123
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app       
    restart: unless-stopped
