version: '3'
services:
  myapp:
    image: myapp
    container_name: jamilzin1APP
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/jamilzin1_db_apirest_test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: dbAPP
    environment:
      - POSTGRES_DB=jamilzin1_db_apirest_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data




