version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: application
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/jamilzin1_db_apirest_test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=SECjam1lz1n
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./target:/app/target  # Mount the 'target' directory as a volume for live reloading

  db:
    image: postgres
    container_name: bancoDados
    environment:
      - POSTGRES_DB=jamilzin1_db_apirest_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SECjam1lz1n
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
